// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseInfos: typeof import('./src/views/MainPage/MerchantManagement/BaseInfos.vue')['default']
    CategoriesList: typeof import('./src/components/Presentational/CategoriesList.vue')['default']
    Container: typeof import('./src/components/Layout/Container.vue')['default']
    GridContainer: typeof import('./src/components/Layout/GridContainer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/views/LoginAndSignup/Login.vue')['default']
    MainPage: typeof import('./src/views/MainPage/MainPage.vue')['default']
    MBaseInfos: typeof import('./src/views/MainPage/MerchantManagement/MBaseInfos.vue')['default']
    MCategories: typeof import('./src/views/MainPage/MerchantManagement/MCategories.vue')['default']
    MerchantManagement: typeof import('./src/views/MainPage/MerchantManagement/MerchantManagement.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContainer: typeof import('./src/components/Layout/NLayoutContainer.vue')['default']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    OdDataTable: typeof import('./src/views/MainPage/OrderManagement/Components/OdDataTable.vue')['default']
    OdSider: typeof import('./src/views/MainPage/OrderManagement/Components/OdSider.vue')['default']
    OrderManagement: typeof import('./src/views/MainPage/OrderManagement/OrderManagement.vue')['default']
    ProdCategoriesSider: typeof import('./src/views/MainPage/ProductManagement/Components/ProdCategoriesSider.vue')['default']
    ProdDataTable: typeof import('./src/views/MainPage/ProductManagement/Components/ProdDataTable.vue')['default']
    ProductManagement: typeof import('./src/views/MainPage/ProductManagement/ProductManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingCartManagement: typeof import('./src/views/MainPage/MerchantManagement/ShoppingCartManagement.vue')['default']
    Signup: typeof import('./src/views/LoginAndSignup/Signup.vue')['default']
  }
}

export {}
