// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/Layout/Container.vue')['default']
    GridContainer: typeof import('./src/components/Layout/GridContainer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NLayoutContainer: typeof import('./src/components/Layout/NLayoutContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
